FROM golang:1.22 AS build-stage
WORKDIR /app
COPY go.mod *.go ./
RUN CGO_ENABLED=0 GOOS=linux go build -o run . 
FROM alpine:3.20.3
WORKDIR /app
COPY --from=build-stage /app/run /app/run 
ENTRYPOINT ["/app/run"]
