FROM golang:1.22 AS build-stage
WORKDIR /app
COPY go.mod *.go ./
RUN CGO_ENABLED=0 GOOS=linux go build -o run . 
FROM alpine:3.20.3
WORKDIR /app
COPY --from=build-stage /app/run /app/run 
HEALTHCHECK --interval=30s \ 
            --timeout=3s \
            --start-period=5s \
            --retries=3 \
              CMD wget  --no-verbose \
                        --tries=1 \
                        --spider \
                        http://localhost:8080/health || exit 1
ENTRYPOINT ["/app/run"]
