FROM golang:1.22 AS build-stage
WORKDIR /app
COPY go.mod *.go ./
RUN CGO_ENABLED=0 GOOS=linux go build -o run . 
FROM alpine:3.20.3
WORKDIR /app
COPY --from=build-stage /app/run /app/run 
HEALTHCHECK --interval=3s \ 
            --timeout=3s \
            --start-period=20s \
            --retries=3 \
              CMD wget --no-verbose \
                            --tries=1 \
                            --spider \
                            --server-response \
                            http://localhost:8080/health 2>&1 | grep -q "HTTP/1.1 2" || exit 1

ENTRYPOINT ["/app/run"]
